
name: Metrics
on:
  schedule:
    - cron: "0 0-23/4 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: 🦑 Personal metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, vue, scala, c, ejs
          plugin_languages_skipped: Mehak-Mehta
          plugin_languages_details: bytes-size, percentage
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: mastered
          plugin_notable: yes
          config_order: base.header, isocalendar, languages, notable, topics
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_limit: 4                   # Limit to 4 entries
          plugin_music_playlist: <iframe src="https://open.spotify.com/embed/playlist/4FEjZLM75QEH8Jao3KGjBy" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe> # Use extracted playlist link
                                            #   (plugin_music_provider and plugin_music_mode will be set automati
          
      - name: 📌 Topics plugin (mastered)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.topics.mastered.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: mastered
          plugins_errors_fatal: ${{ github.repository == 'Mehak-Mehta' }}
          output_action: pull-request
          
      - name: 📌 Aci (mastered)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.personal.aci.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: B       # Display achievements with rank B or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_ignored: octonaut  # Hide octonaut achievement
          plugin_achievements_limit: 0           
