
name: Metrics
on:
  schedule:
    - cron: "0 0-23/4 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: 🦑 Personal metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, vue, scala, c, ejs
          plugin_languages_skipped: Mehak-Mehta
          plugin_languages_details: bytes-size, percentage
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: mastered
          plugin_notable: yes
          config_order: base.header, isocalendar, languages, notable, topics
         
          
      - name: 📌 Topics plugin (mastered)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.topics.mastered.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: mastered
          plugins_errors_fatal: ${{ github.repository == 'Mehak-Mehta' }}
          output_action: pull-request
          
      - name: 📌 Aci (mastered)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.personal.aci.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: A      # Display achievements with rank B or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_ignored: ""  # Hide octonaut achievement
          plugin_achievements_limit: 0   
          
      - name: 📌 music (mastered)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.personal.mu.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_limit: 4                   # Limit to 4 entries
          plugin_music_playlist: https://open.spotify.com/playlist/33pd4jh5Bz8gpyLDiUr4EZ?si=7d4f1fc77eb54537
      - name: habits
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
         filename: metrics.personal.habits.svg
         plugin_habits: yes
         plugin_habits_from: 200       # Use 200 events to compute habits
         plugin_habits_days: 14        # Keep only events from last 14 days
         plugin_habits_facts: yes      # Display facts section
         plugin_habits_charts: yes     # Display charts section
         config_timezone: Asia/Kolkata # Set timezone

